name: prepdevenv
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Prep dev environment'
        required: true
        default: 'Ciao, Ciao'
      home:
        description: 'location'
        required: false
      
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
      echo Hello ${{ github.event.inputs.name }}
      echo in ${{ github.event.inputs.home }}!
      